# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f6267602b67deb9132839a82fc706b1893d27c35eb35a799768c680231a393a676bbd376bbcb216f939dbfaba097cd0b799735f48c965b7705c81f6d866369

test:
  secret_key_base: 4cbe8efc405b2ed16e7849342720274594f3a92a7007552abe636b358e58ede5a2bcb0968dd3b62a46ae4861b7121d936fd5a4f18394f0029c00bfc06ae5c3ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
